### PR TITLE
removed my slider folder

### PR DESCRIPTION
**Pull request by LawSibisi**
removed the slider folder, which had the same copies of index.html and style.css.

### CODE REVIEW

**Review by Rabianzo — COMMENTED** [review]
Noted

**Comment by LawSibisi** [comment]
I had to revert to my backup code due to complications on the current one I had. also had to add responsiveness to my style

**Comment by sidon59** [comment]
Good. im glad you added responsiveness, also check on the styling

**Comment by LawSibisi** [comment]
@sidon59 Thanks, on the Styling I had to center the social media icons. tried moving them around but they ruined the contact page. so I decided to leave everything as it is, Working.

**Review by sidon59 — APPROVED** [review]

**Review by Sinethemba7vitsha — APPROVED** [review]
Changed were made and they are working also added responsiveness to the style

**Review by LundiLanga — APPROVED** [review]
I see the changes. And you also added instructions on how to run your code. Great.

**Comment by LawSibisi** [comment]
Merging Pull requests

**Comment by sidon59** [comment]
perfect!!

**Pull request merged**
